heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200/_cluster/health
    - http://kibana:5601/status
    - http://logstash:9600/?pretty
    - http://reader:8082
    - http://todo:8081
- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_docker_metadata:
- add_process_metadata:
    match_pids: [system.process.ppid]
    target: system.process.parent

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'heartbeat'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup.kibana:
  host: "http://kibana:5601"
setup.dashboards.enabled: true

queue.mem:
  events: 4096
  flush.timeout: 5s

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["elasticsearch:9200"]