heartbeat.monitors:
- type: icmp
  schedule: '@every 10s'
  hosts:
    - elasticsearch
    - kibana
    - logstash
    - apm-server

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']

setup.kibana:
  host: "http://kibana:5601"

xpack.monitoring.enabled: true