packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

processors:
- add_docker_metadata:

packetbeat.protocols:
- type: icmp
  enabled: true
- type: http
  ports: [9200, 9300, 5000, 9600, 5555, 5601, 8200, 8082, 8081]
  hide_keywords: ["pass", "password", "passwd"]
  send_headers: ["User-Agent", "Cookie", "Set-Cookie"]
  split_cookie: true
  real_ip_header: "X-Forwarded-For"

output.kafka:
  hosts: ["localhost:9092"]
  topic: 'packetbeat'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup.kibana:
  host: "localhost:5601"

queue.mem:
  events: 4096
  flush.timeout: 5s

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["localhost:9200"]