apm-server:
  host: apm-server:8200

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'apm-server'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup:
  kibana:
    host: "http://kibana:5601"
  dashboards:
    enabled: true