output.kafka:
  hosts: ["kafka:9092"]
  topic: 'metricbeat'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

setup.kibana:
  host: "http://kibana:5601"

metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ["http://kibana:5601"]
  xpack.enabled: true

xpack.monitoring:
  enabled: true