---
server.name: kibana
server.host: "0"
elasticsearch.url: elasticsearch:9200

xpack.monitoring.kibana.collection.enabled: false # we use metricbeat instead
xpack.monitoring.collection.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true